/// OpenAPI documentation for signapps-it-assets (port 3015).
use utoipa::{
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
    Modify, OpenApi,
};

pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        // ── Hardware ──────────────────────────────────────────────────────────
        crate::handlers::hardware::list_hardware,
        crate::handlers::hardware::get_hardware,
        crate::handlers::hardware::create_hardware,
        crate::handlers::hardware::update_hardware,
        crate::handlers::hardware::delete_hardware,
        // ── Agent ─────────────────────────────────────────────────────────────
        crate::handlers::agent::register_agent,
        crate::handlers::agent::agent_heartbeat,
        crate::handlers::agent::get_agent_config,
        crate::handlers::agent::report_hardware_inventory,
        crate::handlers::agent::report_software_inventory,
        crate::handlers::agent::get_pending_scripts,
        crate::handlers::agent::queue_script,
        crate::handlers::agent::report_script_result,
        crate::handlers::agent::create_enrollment_token,
        crate::handlers::agent::download_agent,
        crate::handlers::agent::report_services,
        crate::handlers::agent::list_hardware_services,
        // ── Automation ────────────────────────────────────────────────────────
        crate::handlers::automation::list_rules,
        crate::handlers::automation::create_rule,
        crate::handlers::automation::get_rule,
        crate::handlers::automation::update_rule,
        crate::handlers::automation::delete_rule,
        crate::handlers::automation::list_executions,
        // ── CMDB ──────────────────────────────────────────────────────────────
        crate::handlers::cmdb::list_cis,
        crate::handlers::cmdb::create_ci,
        crate::handlers::cmdb::get_ci,
        crate::handlers::cmdb::update_ci,
        crate::handlers::cmdb::delete_ci,
        crate::handlers::cmdb::list_ci_relationships,
        crate::handlers::cmdb::create_ci_relationship,
        crate::handlers::cmdb::delete_ci_relationship,
        crate::handlers::cmdb::ci_impact,
        crate::handlers::cmdb::list_change_requests,
        crate::handlers::cmdb::create_change_request,
        crate::handlers::cmdb::get_change_request,
        crate::handlers::cmdb::update_change_status,
        crate::handlers::cmdb::import_ldap,
        // ── Commands ──────────────────────────────────────────────────────────
        crate::handlers::commands::queue_agent_command,
        crate::handlers::commands::get_pending_commands,
        crate::handlers::commands::update_command_status,
        crate::handlers::commands::list_hardware_commands,
        // ── Custom fields ─────────────────────────────────────────────────────
        crate::handlers::custom_fields::list_field_defs,
        crate::handlers::custom_fields::create_field_def,
        crate::handlers::custom_fields::update_field_def,
        crate::handlers::custom_fields::delete_field_def,
        crate::handlers::custom_fields::get_hardware_fields,
        crate::handlers::custom_fields::set_field_value,
        // ── Device docs ───────────────────────────────────────────────────────
        crate::handlers::device_docs::list_device_docs,
        crate::handlers::device_docs::create_device_doc,
        // ── Files ─────────────────────────────────────────────────────────────
        crate::handlers::files::push_file_to_machine,
        crate::handlers::files::agent_upload_file,
        crate::handlers::files::agent_download_file,
        crate::handlers::files::list_hardware_files,
        // ── Groups & Tags ─────────────────────────────────────────────────────
        crate::handlers::groups::list_groups,
        crate::handlers::groups::create_group,
        crate::handlers::groups::get_group,
        crate::handlers::groups::update_group,
        crate::handlers::groups::delete_group,
        crate::handlers::groups::list_members,
        crate::handlers::groups::add_member,
        crate::handlers::groups::remove_member,
        crate::handlers::groups::list_tags,
        crate::handlers::groups::create_tag,
        crate::handlers::groups::delete_tag,
        crate::handlers::groups::assign_tag,
        crate::handlers::groups::unassign_tag,
        crate::handlers::groups::list_hardware_tags,
        // ── Monitoring ────────────────────────────────────────────────────────
        crate::handlers::monitoring::get_metrics,
        crate::handlers::monitoring::list_alert_rules,
        crate::handlers::monitoring::create_alert_rule,
        crate::handlers::monitoring::delete_alert_rule,
        crate::handlers::monitoring::list_alerts,
        crate::handlers::monitoring::resolve_alert,
        crate::handlers::monitoring::ingest_event_logs,
        crate::handlers::monitoring::get_event_logs,
        crate::handlers::monitoring::fleet_overview,
        crate::handlers::monitoring::list_components,
        crate::handlers::monitoring::create_component,
        crate::handlers::monitoring::update_component,
        crate::handlers::monitoring::delete_component,
        crate::handlers::monitoring::list_licenses,
        crate::handlers::monitoring::get_license,
        crate::handlers::monitoring::create_license,
        crate::handlers::monitoring::update_license,
        crate::handlers::monitoring::delete_license,
        crate::handlers::monitoring::list_network_interfaces,
        crate::handlers::monitoring::create_network_interface,
        crate::handlers::monitoring::update_network_interface,
        crate::handlers::monitoring::delete_network_interface,
        crate::handlers::monitoring::list_maintenance_windows,
        crate::handlers::monitoring::create_maintenance_window,
        crate::handlers::monitoring::update_maintenance_window,
        crate::handlers::monitoring::delete_maintenance_window,
        crate::handlers::monitoring::get_health_score,
        // ── Network ───────────────────────────────────────────────────────────
        crate::handlers::network::scan_network,
        crate::handlers::network::list_discoveries,
        crate::handlers::network::add_discovery_to_inventory,
        crate::handlers::network::port_scan,
        crate::handlers::network::query_snmp,
        // ── Packages ──────────────────────────────────────────────────────────
        crate::handlers::packages::list_packages,
        crate::handlers::packages::get_package,
        crate::handlers::packages::create_package,
        crate::handlers::packages::update_package,
        crate::handlers::packages::delete_package,
        crate::handlers::packages::deploy_package,
        crate::handlers::packages::get_agent_pending_packages,
        crate::handlers::packages::update_deployment_status,
        // ── Patches ───────────────────────────────────────────────────────────
        crate::handlers::patches::report_available_patches,
        crate::handlers::patches::list_patches,
        crate::handlers::patches::approve_patch,
        crate::handlers::patches::reject_patch,
        crate::handlers::patches::deploy_patch,
        crate::handlers::patches::patch_compliance,
        crate::handlers::patches::rollback_patch,
        // ── Playbooks ─────────────────────────────────────────────────────────
        crate::handlers::playbooks::list_playbooks,
        crate::handlers::playbooks::create_playbook,
        crate::handlers::playbooks::get_playbook,
        crate::handlers::playbooks::update_playbook,
        crate::handlers::playbooks::delete_playbook,
        crate::handlers::playbooks::run_playbook,
        crate::handlers::playbooks::list_playbook_runs,
        // ── Policies ──────────────────────────────────────────────────────────
        crate::handlers::policies::list_policies,
        crate::handlers::policies::list_policies_tree,
        crate::handlers::policies::get_policy,
        crate::handlers::policies::create_policy,
        crate::handlers::policies::update_policy,
        crate::handlers::policies::delete_policy,
        crate::handlers::policies::assign_policy,
        crate::handlers::policies::list_assignments,
        crate::handlers::policies::get_agent_policies,
        crate::handlers::policies::report_compliance,
        crate::handlers::policies::compliance_summary,
        // ── Remote ────────────────────────────────────────────────────────────
        crate::handlers::remote_ws::agent_remote_ws,
        crate::handlers::remote_ws::admin_remote_viewer,
        crate::handlers::remote_ws::start_remote_session,
        crate::handlers::remote_ws::stop_remote_session,
        crate::handlers::remote_ws::list_recordings,
        // ── Script Library ────────────────────────────────────────────────────
        crate::handlers::script_library::list_scripts,
        crate::handlers::script_library::create_script,
        crate::handlers::script_library::get_script,
        crate::handlers::script_library::update_script,
        crate::handlers::script_library::delete_script,
        crate::handlers::script_library::run_library_script,
        crate::handlers::script_library::list_schedules,
        crate::handlers::script_library::create_schedule,
        crate::handlers::script_library::delete_schedule,
        // ── Security ──────────────────────────────────────────────────────────
        crate::handlers::security::report_antivirus,
        crate::handlers::security::get_antivirus_status,
        crate::handlers::security::av_fleet_summary,
        crate::handlers::security::report_encryption,
        crate::handlers::security::get_encryption_status,
        crate::handlers::security::encryption_fleet_summary,
        // ── Software Policies ─────────────────────────────────────────────────
        crate::handlers::software_policies::list_software_policies,
        crate::handlers::software_policies::create_software_policy,
        crate::handlers::software_policies::check_software_compliance,
        // ── Tickets ───────────────────────────────────────────────────────────
        crate::handlers::tickets::create_ticket,
        crate::handlers::tickets::list_tickets,
        crate::handlers::tickets::ticket_stats,
        crate::handlers::tickets::get_ticket,
        crate::handlers::tickets::update_ticket,
        crate::handlers::tickets::delete_ticket,
        crate::handlers::tickets::add_comment,
        crate::handlers::tickets::log_time_entry,
        crate::handlers::tickets::list_psa_integrations,
        crate::handlers::tickets::create_psa_integration,
        crate::handlers::tickets::update_psa_integration,
        crate::handlers::tickets::delete_psa_integration,
        // ── Wake-on-LAN ───────────────────────────────────────────────────────
        crate::handlers::wol::wake_on_lan,
    ),
    components(schemas(
        // Hardware
        crate::models::HardwareAsset,
        crate::models::CreateHardwareReq,
        crate::models::UpdateHardwareReq,
        // Agent
        crate::handlers::agent::RegisterAgentReq,
        crate::handlers::agent::HeartbeatReq,
        crate::handlers::agent::AgentConfig,
        crate::handlers::agent::HardwareInventoryReq,
        crate::handlers::agent::SoftwareInventoryReq,
        crate::handlers::agent::SoftwareEntry,
        crate::handlers::agent::QueueScriptReq,
        crate::handlers::agent::ScriptResultReq,
        crate::handlers::agent::EnrollmentTokenRow,
        crate::handlers::agent::ServiceEntry,
        crate::handlers::agent::ReportServicesReq,
        // Automation
        crate::handlers::automation::AutomationRule,
        crate::handlers::automation::CreateRuleReq,
        crate::handlers::automation::UpdateRuleReq,
        crate::handlers::automation::AutomationExecution,
        // CMDB
        crate::handlers::cmdb::ConfigurationItem,
        crate::handlers::cmdb::CreateCiReq,
        crate::handlers::cmdb::UpdateCiReq,
        crate::handlers::cmdb::CiRelationship,
        crate::handlers::cmdb::CreateCiRelReq,
        crate::handlers::cmdb::ChangeRequest,
        crate::handlers::cmdb::CreateChangeReq,
        crate::handlers::cmdb::UpdateChangeStatusReq,
        crate::handlers::cmdb::LdapImportReq,
        // Commands
        crate::handlers::commands::AgentCommand,
        crate::handlers::commands::QueueCommandReq,
        crate::handlers::commands::UpdateCommandStatusReq,
        // Custom fields
        crate::handlers::custom_fields::CustomFieldDef,
        crate::handlers::custom_fields::CreateFieldDefReq,
        crate::handlers::custom_fields::UpdateFieldDefReq,
        crate::handlers::custom_fields::CustomFieldValue,
        crate::handlers::custom_fields::HardwareCustomFields,
        crate::handlers::custom_fields::SetFieldValueReq,
        // Device docs
        crate::handlers::device_docs::DeviceDoc,
        crate::handlers::device_docs::CreateDocReq,
        // Files
        crate::handlers::files::FileTransfer,
        crate::handlers::files::PushFileReq,
        crate::handlers::files::AgentUploadReq,
        // Groups & Tags
        crate::handlers::groups::DeviceGroup,
        crate::handlers::groups::CreateGroupReq,
        crate::handlers::groups::UpdateGroupReq,
        crate::handlers::groups::DeviceTag,
        crate::handlers::groups::CreateTagReq,
        crate::handlers::groups::MembershipReq,
        crate::handlers::groups::TagAssignReq,
        crate::handlers::groups::GroupMember,
        crate::handlers::groups::HardwareTag,
        // Monitoring
        crate::handlers::monitoring::MetricsQuery,
        crate::handlers::monitoring::MetricRow,
        crate::handlers::monitoring::AlertRule,
        crate::handlers::monitoring::CreateAlertRuleReq,
        crate::handlers::monitoring::AlertRow,
        crate::handlers::monitoring::LogEntry,
        crate::handlers::monitoring::IngestLogsReq,
        crate::handlers::monitoring::EventLogRow,
        crate::handlers::monitoring::LogQuery,
        crate::handlers::monitoring::FleetOverview,
        crate::handlers::monitoring::OsCount,
        crate::handlers::monitoring::StatusCount,
        crate::handlers::monitoring::MachineRow,
        crate::handlers::monitoring::ComponentRow,
        crate::handlers::monitoring::CreateComponentReq,
        crate::handlers::monitoring::UpdateComponentReq,
        crate::handlers::monitoring::LicenseRow,
        crate::handlers::monitoring::LicenseWithUsage,
        crate::handlers::monitoring::CreateLicenseReq,
        crate::handlers::monitoring::UpdateLicenseReq,
        crate::handlers::monitoring::NetworkInterfaceRow,
        crate::handlers::monitoring::CreateNetworkInterfaceReq,
        crate::handlers::monitoring::UpdateNetworkInterfaceReq,
        crate::handlers::monitoring::MaintenanceWindowRow,
        crate::handlers::monitoring::CreateMaintenanceWindowReq,
        crate::handlers::monitoring::UpdateMaintenanceWindowReq,
        crate::handlers::monitoring::HealthScore,
        // Network
        crate::handlers::network::NetworkDiscovery,
        crate::handlers::network::ScanSubnetReq,
        crate::handlers::network::ScanResult,
        crate::handlers::network::DiscoveryEntry,
        crate::handlers::network::PortScanReq,
        crate::handlers::network::PortScanResult,
        crate::handlers::network::AddToInventoryReq,
        // Packages
        crate::handlers::packages::SoftwarePackage,
        crate::handlers::packages::CreatePackageRequest,
        crate::handlers::packages::UpdatePackageRequest,
        crate::handlers::packages::Deployment,
        crate::handlers::packages::DeployRequest,
        crate::handlers::packages::PendingInstall,
        crate::handlers::packages::UpdateDeploymentStatusRequest,
        // Patches
        crate::handlers::patches::ReportPatchesReq,
        crate::handlers::patches::PatchEntry,
        crate::handlers::patches::PatchRow,
        crate::handlers::patches::ComplianceStats,
        crate::handlers::patches::SeverityCount,
        crate::handlers::patches::DeployPatchReq,
        // Playbooks
        crate::handlers::playbooks::PlaybookRow,
        crate::handlers::playbooks::CreatePlaybookReq,
        crate::handlers::playbooks::UpdatePlaybookReq,
        crate::handlers::playbooks::PlaybookRunRow,
        crate::handlers::playbooks::RunPlaybookReq,
        // Policies
        crate::handlers::policies::Policy,
        crate::handlers::policies::PolicyWithChildren,
        crate::handlers::policies::CreatePolicyRequest,
        crate::handlers::policies::UpdatePolicyRequest,
        crate::handlers::policies::AssignPolicyRequest,
        crate::handlers::policies::PolicyAssignment,
        crate::handlers::policies::ComplianceReport,
        crate::handlers::policies::ComplianceSummary,
        crate::handlers::policies::NonCompliantMachine,
        // Remote
        crate::handlers::remote_ws::StartSessionReq,
        crate::handlers::remote_ws::SessionResp,
        crate::handlers::remote_ws::RecordingRow,
        // Script library
        crate::handlers::script_library::ScriptLibraryEntry,
        crate::handlers::script_library::CreateScriptReq,
        crate::handlers::script_library::UpdateScriptReq,
        crate::handlers::script_library::RunScriptFromLibraryReq,
        crate::handlers::script_library::ScheduledScript,
        crate::handlers::script_library::CreateScheduleReq,
        // Security
        crate::handlers::security::ReportAntivirusReq,
        crate::handlers::security::AntivirusStatusRow,
        crate::handlers::security::AvFleetSummary,
        crate::handlers::security::ReportEncryptionReq,
        crate::handlers::security::DriveEncryptionEntry,
        crate::handlers::security::EncryptionStatusRow,
        crate::handlers::security::EncryptionFleetSummary,
        // Software policies
        crate::handlers::software_policies::SoftwarePolicy,
        crate::handlers::software_policies::CreateSoftwarePolicyReq,
        crate::handlers::software_policies::SoftwarePolicyCheckResult,
        crate::handlers::software_policies::PolicyViolation,
        // Tickets
        crate::handlers::tickets::Ticket,
        crate::handlers::tickets::TicketComment,
        crate::handlers::tickets::TicketTimeEntry,
        crate::handlers::tickets::TicketDetail,
        crate::handlers::tickets::CreateTicketReq,
        crate::handlers::tickets::UpdateTicketReq,
        crate::handlers::tickets::AddCommentReq,
        crate::handlers::tickets::AddTimeEntryReq,
        crate::handlers::tickets::TicketStats,
        crate::handlers::tickets::PriorityCount,
        crate::handlers::tickets::PsaIntegrationRow,
        crate::handlers::tickets::CreatePsaIntegrationReq,
        crate::handlers::tickets::UpdatePsaIntegrationReq,
        // WoL
        crate::handlers::wol::WolResponse,
    )),
    modifiers(&SecurityAddon),
    info(
        title = "SignApps IT Assets API",
        version = "1.0.0",
        description = "IT asset management — hardware inventory, agent management, patches, policies, tickets, playbooks, remote access"
    )
)]
pub struct ItAssetsApiDoc;
