/**
 * App logo resolver — 200 logos served locally from /app-logos/.
 * Fallback: Google favicon API for unknown apps.
 *
 * Resolution:
 * 1. app.icon from source → used directly if valid
 * 2. getAppLogo() → local /app-logos/{name}.png
 * 3. Google favicon → https://www.google.com/s2/favicons?domain={name}.com&sz=128
 */

/** Map app id/name to local logo filename */
const APP_LOGO_MAP: Record<string, string> = {
  "2fauth": "2fauth",
  activepieces: "activepieces",
  activeworkflow: "activeworkflow",
  "actual-server": "actual-server",
  acunetix: "acunetix",
  adguard: "adguard",
  "adguard-home": "adguard-home",
  adguardhome: "adguardhome",
  adminer: "adminer",
  alist: "alist",
  anse: "anse",
  ansible: "ansible",
  appsmith: "appsmith",
  arangodb: "arangodb",
  archivebox: "archivebox",
  audacity: "audacity",
  audiobookshelf: "audiobookshelf",
  authentik: "authentik",
  autobrr: "autobrr",
  ayon: "ayon",
  baserow: "baserow",
  bazarr: "bazarr",
  beszel: "beszel",
  bitwarden: "bitwarden",
  blender: "blender",
  bookstack: "bookstack",
  brave: "brave",
  browserless: "browserless",
  btop: "btop",
  budibase: "budibase",
  cachet: "cachet",
  caddy: "caddy",
  cadvisor: "cadvisor",
  calcom: "calcom",
  calibre: "calibre",
  "calibre-web": "calibre-web",
  changedetection: "changedetection",
  chatbotui: "chatbotui",
  chatpad: "chatpad",
  chatwoot: "chatwoot",
  chrome: "chrome",
  chromium: "chromium",
  cloudbeaver: "cloudbeaver",
  cloudflared: "cloudflared",
  cockroachdb: "cockroachdb",
  "code-server": "code-server",
  coder: "coder",
  composetoolbox: "composetoolbox",
  confluence: "confluence",
  consul: "consul",
  convertx: "convertx",
  coolify: "coolify",
  crafty: "crafty",
  crawlab: "crawlab",
  crowdsec: "crowdsec",
  ctfd: "ctfd",
  "cube-js": "cube-js",
  cyberchef: "cyberchef",
  dashdot: "dashdot",
  dashy: "dashy",
  davis: "davis",
  dbgate: "dbgate",
  deluge: "deluge",
  dependencytrack: "dependencytrack",
  directus: "directus",
  discord: "discord",
  discourse: "discourse",
  diskstation: "diskstation",
  diun: "diun",
  docat: "docat",
  docker: "docker",
  dockge: "dockge",
  dockhand: "dockhand",
  dockpeek: "dockpeek",
  docmost: "docmost",
  doku: "doku",
  dokuwiki: "dokuwiki",
  dozzle: "dozzle",
  drawio: "drawio",
  drone: "drone",
  drupal: "drupal",
  duplicati: "duplicati",
  elasticsearch: "elasticsearch",
  element: "element",
  emby: "emby",
  emqx: "emqx",
  erugo: "erugo",
  esphome: "esphome",
  excalidraw: "excalidraw",
  factorio: "factorio",
  faraday: "faraday",
  farmos: "farmos",
  fasten: "fasten",
  fastfetch: "fastfetch",
  filebrowser: "filebrowser",
  "filebrowser-quantum": "filebrowser-quantum",
  filedrop: "filedrop",
  filegator: "filegator",
  "financial-freedom": "financial-freedom",
  firefly: "firefly",
  "firefly-iii": "firefly-iii",
  firefox: "firefox",
  flame: "flame",
  flarum: "flarum",
  flipt: "flipt",
  flowise: "flowise",
  focalboard: "focalboard",
  forgejo: "forgejo",
  freshrss: "freshrss",
  frigate: "frigate",
  gemdigest: "gemdigest",
  genmon: "genmon",
  ghost: "ghost",
  ghostfolio: "ghostfolio",
  gitea: "gitea",
  "gitea-mirror": "gitea-mirror",
  github: "github",
  gitlab: "gitlab",
  glances: "glances",
  gluetun: "gluetun",
  gotify: "gotify",
  grafana: "grafana",
  grav: "grav",
  grocy: "grocy",
  guacamole: "guacamole",
  handbrake: "handbrake",
  harbor: "harbor",
  hasura: "hasura",
  healthchecks: "healthchecks",
  hedgedoc: "hedgedoc",
  heimdall: "heimdall",
  hetty: "hetty",
  homarr: "homarr",
  homeassistant: "homeassistant",
  homebox: "homebox",
  homebridge: "homebridge",
  homepage: "homepage",
  homer: "homer",
  hoppscotch: "hoppscotch",
  huginn: "huginn",
  ihatemoney: "ihatemoney",
  immich: "immich",
  "immich-aio-alpine": "immich-aio-alpine",
  "immich-kiosk": "immich-kiosk",
  invidious: "invidious",
  "invoice-ninja": "invoice-ninja",
  "it-tools": "it-tools",
  jackett: "jackett",
  jdownloader2: "jdownloader2",
  jellyfin: "jellyfin",
  jellyseerr: "jellyseerr",
  jenkins: "jenkins",
  jira: "jira",
  jitsi: "jitsi",
  joplin: "joplin",
  kasm: "kasm",
  kavita: "kavita",
  keycloak: "keycloak",
  kitchenowl: "kitchenowl",
  koel: "koel",
  komga: "komga",
  kopia: "kopia",
  kubernetes: "kubernetes",
  labelstudio: "labelstudio",
  lancache: "lancache",
  lemmy: "lemmy",
  libredesk: "libredesk",
  libretranslate: "libretranslate",
  lidarr: "lidarr",
  linkstack: "linkstack",
  linkwarden: "linkwarden",
  listmonk: "listmonk",
  "lobe-chat": "lobe-chat",
  lsdvr: "lsdvr",
  lucky: "lucky",
  mailpit: "mailpit",
  manyfold: "manyfold",
  mariadb: "mariadb",
  mastodon: "mastodon",
  matomo: "matomo",
  mattermost: "mattermost",
  "maybe-finance": "maybe-finance",
  mealie: "mealie",
  mediawiki: "mediawiki",
  medusa: "medusa",
  meilisearch: "meilisearch",
  memos: "memos",
  metasploit: "metasploit",
  metube: "metube",
  microbin: "microbin",
  mind: "mind",
  "minecraft-server": "minecraft-server",
  mineos: "mineos",
  miniflux: "miniflux",
  minio: "minio",
  mkvtoolnix: "mkvtoolnix",
  mobsf: "mobsf",
  mongo: "mongo",
  mongodb: "mongodb",
  monica: "monica",
  moodle: "moodle",
  morphos: "morphos",
  "mumble-server": "mumble-server",
  myspeed: "myspeed",
  mysql: "mysql",
  n8n: "n8n",
  navidrome: "navidrome",
  ncdu: "ncdu",
  nessus: "nessus",
  netalertx: "netalertx",
  netdata: "netdata",
  nexpose: "nexpose",
  nextchat: "nextchat",
  nextcloud: "nextcloud",
  "nextcloud-ls": "nextcloud-ls",
  nexterm: "nexterm",
  nginx: "nginx",
  nginxproxymanager: "nginxproxymanager",
  nightscout: "nightscout",
  nocodb: "nocodb",
  "node-red": "node-red",
  nodered: "nodered",
  notifiarr: "notifiarr",
  ntfy: "ntfy",
  nzbget: "nzbget",
  obsidian: "obsidian",
  octoprint: "octoprint",
  odoo: "odoo",
  ohmyform: "ohmyform",
  "ollama-amd": "ollama-amd",
  "ollama-cpu": "ollama-cpu",
  "ollama-nvidia": "ollama-nvidia",
  omnitools: "omnitools",
  onedev: "onedev",
  onlyoffice: "onlyoffice",
  "open-webui": "open-webui",
  opencart: "opencart",
  openclaw: "openclaw",
  opencti: "opencti",
  openhab: "openhab",
  openobserve: "openobserve",
  openspeedtest: "openspeedtest",
  openvas: "openvas",
  outline: "outline",
  overseerr: "overseerr",
  owncloud: "owncloud",
  paperless: "paperless",
  "paperless-ngx": "paperless-ngx",
  passbolt: "passbolt",
  passwordpusher: "passwordpusher",
  pd3f: "pd3f",
  penpot: "penpot",
  peppermint: "peppermint",
  petio: "petio",
  photoprism: "photoprism",
  phpbb: "phpbb",
  phpmyadmin: "phpmyadmin",
  pihole: "pihole",
  "pingvin-share": "pingvin-share",
  piped: "piped",
  piwigo: "piwigo",
  plane: "plane",
  planka: "planka",
  "planka-v2": "planka-v2",
  "plant-it": "plant-it",
  plausible: "plausible",
  plex: "plex",
  pocketbase: "pocketbase",
  pocketid: "pocketid",
  portainer: "portainer",
  portracker: "portracker",
  postgresql: "postgresql",
  postiz: "postiz",
  privatebin: "privatebin",
  "project-management": "project-management",
  prometheus: "prometheus",
  prowlarr: "prowlarr",
  "pterodactyl-panel": "pterodactyl-panel",
  "pterodactyl-wings": "pterodactyl-wings",
  pyload: "pyload",
  qbittorrent: "qbittorrent",
  rabbitmq: "rabbitmq",
  radarr: "radarr",
  rallly: "rallly",
  rancher: "rancher",
  "reactive-resume": "reactive-resume",
  readarr: "readarr",
  readeck: "readeck",
  redis: "redis",
  redmine: "redmine",
  rengine: "rengine",
  "resilio-sync": "resilio-sync",
  "rocket-chat": "rocket-chat",
  rocketchat: "rocketchat",
  romm: "romm",
  "rss-bridge": "rss-bridge",
  rustfs: "rustfs",
  ryot: "ryot",
  sabnzbd: "sabnzbd",
  scrutiny: "scrutiny",
  seafile: "seafile",
  seekr: "seekr",
  semaphore: "semaphore",
  sentry: "sentry",
  sftpgo: "sftpgo",
  sharex: "sharex",
  "siyuan-note": "siyuan-note",
  slack: "slack",
  smokeping: "smokeping",
  snapdrop: "snapdrop",
  "social-analyzer": "social-analyzer",
  sonarqube: "sonarqube",
  sonarr: "sonarr",
  spacedrive: "spacedrive",
  "speedtest-tracker": "speedtest-tracker",
  spiderfoot: "spiderfoot",
  spoolman: "spoolman",
  "stalwart-mail": "stalwart-mail",
  "stirling-pdf": "stirling-pdf",
  storyteller: "storyteller",
  strapi: "strapi",
  stremio: "stremio",
  suitecrm: "suitecrm",
  supabase: "supabase",
  syncthing: "syncthing",
  tailscale: "tailscale",
  tandoor: "tandoor",
  tautulli: "tautulli",
  teammapper: "teammapper",
  teldrive: "teldrive",
  terraform: "terraform",
  thelounge: "thelounge",
  thingsboard: "thingsboard",
  threadfin: "threadfin",
  tianji: "tianji",
  traccar: "traccar",
  traefik: "traefik",
  transmission: "transmission",
  trilium: "trilium",
  trip: "trip",
  tududi: "tududi",
  twingate: "twingate",
  uisp: "uisp",
  umami: "umami",
  "unifi-network-application": "unifi-network-application",
  unmanic: "unmanic",
  "uptime-kuma": "uptime-kuma",
  uptimekuma: "uptimekuma",
  vault: "vault",
  vaultwarden: "vaultwarden",
  vert: "vert",
  victoriametrics: "victoriametrics",
  vikunja: "vikunja",
  wallabag: "wallabag",
  wallos: "wallos",
  warracker: "warracker",
  wastebin: "wastebin",
  watchstate: "watchstate",
  webgoat: "webgoat",
  webtop: "webtop",
  "wg-easy": "wg-easy",
  "wg-easy-v15": "wg-easy-v15",
  wikijs: "wikijs",
  wireguard: "wireguard",
  wishlist: "wishlist",
  wordpress: "wordpress",
  "write-freely": "write-freely",
  xteve: "xteve",
  yopass: "yopass",
  zigbee2mqtt: "zigbee2mqtt",
  zipline: "zipline",
  zotero: "zotero",
  "draw.io": "drawio",
  "home-assistant": "homeassistant",
  "pi-hole": "pihole",
  postgres: "postgresql",
  "rocket.chat": "rocketchat",
  uptime: "uptime-kuma",
  wiki: "wikijs",
  "wiki.js": "wikijs",
};

/** Available logo sizes */
export type LogoSize = 32 | 64 | 128;

/**
 * Get logo for an app at a specific size.
 *
 * Available sizes: 32px (compact lists), 64px (cards, default), 128px (detail dialogs).
 * All logos are pre-resized PNG with transparent background, centered on square canvas.
 *
 * Resolution:
 * 1. Local match in /app-logos/{size}/{name}.png (200 logos x 3 sizes)
 * 2. Docker image name match
 * 3. Fuzzy match (contains)
 * 4. Google favicon fallback
 */
export function getAppLogo(
  appIdOrName: string,
  dockerImage?: string,
  size: LogoSize = 64,
): string {
  const key = appIdOrName.toLowerCase().trim();
  const sizeDir = size === 64 ? "" : `${size}/`;

  // Direct match
  if (APP_LOGO_MAP[key]) {
    return `/app-logos/${sizeDir}${APP_LOGO_MAP[key]}.png`;
  }

  // Strip Docker prefixes
  const stripped = key
    .replace(/^linuxserver\//, "")
    .replace(/^lscr\.io\/linuxserver\//, "")
    .replace(/^ghcr\.io\/[^/]+\//, "")
    .replace(/^docker\.io\//, "")
    .replace(/^library\//, "");
  if (APP_LOGO_MAP[stripped]) {
    return `/app-logos/${sizeDir}${APP_LOGO_MAP[stripped]}.png`;
  }

  // Docker image base name
  if (dockerImage) {
    const imgBase =
      dockerImage.split(":")[0].split("/").pop()?.toLowerCase() || "";
    if (APP_LOGO_MAP[imgBase]) {
      return `/app-logos/${sizeDir}${APP_LOGO_MAP[imgBase]}.png`;
    }
  }

  // Fuzzy match
  for (const [logoKey, filename] of Object.entries(APP_LOGO_MAP)) {
    if (key.includes(logoKey) || logoKey.includes(key)) {
      return `/app-logos/${sizeDir}${filename}.png`;
    }
  }

  // Fallback: Google favicon API
  const sanitized = key.replace(/[^a-z0-9-]/g, "");
  return `https://www.google.com/s2/favicons?domain=${sanitized}.com&sz=${size}`;
}
