#!/usr/bin/env node
/**
 * A11y Catalog Generator — Phase E1a
 *
 * Usage: node scripts/a11y-catalog.mjs
 *
 * Reads the output of `npx eslint src/ --format json` (via spawnSync,
 * no shell — safe) and produces:
 *   docs/bug-sweep/a11y-lint-catalog.md
 * with violations grouped by:
 *   1. Top rules by count (most impactful to fix first)
 *   2. Top files by count (hot spots)
 *
 * If docs/bug-sweep/a11y-axe-baseline.json exists (generated by
 * e2e/a11y-audit.spec.ts), also produces:
 *   docs/bug-sweep/a11y-axe-summary.md
 */
import { spawnSync } from "node:child_process";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import path from "node:path";

// ── Path resolution (Windows-safe) ──────────────────────────────────────────

const SCRIPT_DIR_RAW = path.dirname(new URL(import.meta.url).pathname);
// On Windows, file:// URL pathname returns "/C:/Prog/..." — strip the leading "/"
const SCRIPT_DIR =
  SCRIPT_DIR_RAW.startsWith("/") && /^\/[A-Za-z]:/.test(SCRIPT_DIR_RAW)
    ? SCRIPT_DIR_RAW.slice(1)
    : SCRIPT_DIR_RAW;
const CLIENT_DIR = path.resolve(SCRIPT_DIR, "..");
const PROJECT_ROOT = path.resolve(CLIENT_DIR, "..");
const OUT_MD = path.join(
  PROJECT_ROOT,
  "docs",
  "bug-sweep",
  "a11y-lint-catalog.md",
);

// ── Run ESLint and parse JSON ───────────────────────────────────────────────

console.log("Running eslint with JSON reporter (30-60 s)…");

// Invoke the eslint CLI JS entry point via node directly. This avoids
// npx (which requires shell on Windows and triggers security-hook
// concerns) and works cross-platform. No shell means no injection risk
// even though the args are hardcoded.
const eslintBin = path.join(
  CLIENT_DIR,
  "node_modules",
  "eslint",
  "bin",
  "eslint.js",
);
const result = spawnSync(
  process.execPath,
  [eslintBin, "src/", "--format", "json", "--no-error-on-unmatched-pattern"],
  {
    cwd: CLIENT_DIR,
    encoding: "utf-8",
    maxBuffer: 100 * 1024 * 1024,
  },
);

const raw = result.stdout || "";
if (!raw.trim().startsWith("[")) {
  console.error("ESLint did not return JSON. stderr:");
  console.error(result.stderr?.slice(0, 1000) || "(empty)");
  console.error("stdout head:", raw.slice(0, 200));
  process.exit(1);
}

const results = JSON.parse(raw);

// Flatten: keep only jsx-a11y messages
const a11yMessages = [];
for (const fileResult of results) {
  for (const msg of fileResult.messages) {
    if (msg.ruleId && msg.ruleId.startsWith("jsx-a11y/")) {
      a11yMessages.push({
        file: path
          .relative(PROJECT_ROOT, fileResult.filePath)
          .replace(/\\/g, "/"),
        rule: msg.ruleId,
      });
    }
  }
}

// Group by rule
const byRule = new Map();
for (const m of a11yMessages) {
  byRule.set(m.rule, (byRule.get(m.rule) || 0) + 1);
}
const ruleEntries = [...byRule.entries()].sort((a, b) => b[1] - a[1]);

// Group by file
const byFile = new Map();
for (const m of a11yMessages) {
  byFile.set(m.file, (byFile.get(m.file) || 0) + 1);
}
const fileEntries = [...byFile.entries()].sort((a, b) => b[1] - a[1]);

// Rule × file pairs
const byRuleFile = new Map();
for (const m of a11yMessages) {
  const k = `${m.rule}::${m.file}`;
  byRuleFile.set(k, (byRuleFile.get(k) || 0) + 1);
}

// Build markdown
const now = new Date().toISOString().slice(0, 10);
const lines = [];
lines.push(`# A11y Lint Catalog — ${now}`);
lines.push("");
lines.push(`Source: \`eslint-plugin-jsx-a11y\` on \`client/src/**/*.{ts,tsx}\``);
lines.push(`Generated by: \`client/scripts/a11y-catalog.mjs\``);
lines.push("");
lines.push(`**Total jsx-a11y warnings:** ${a11yMessages.length}`);
lines.push(`**Distinct rules:** ${ruleEntries.length}`);
lines.push(`**Distinct files affected:** ${fileEntries.length}`);
lines.push("");

lines.push("## Top rules by count");
lines.push("");
lines.push("| Rule | Count | Top 3 files |");
lines.push("|---|---|---|");
for (const [rule, count] of ruleEntries) {
  const topFiles = [...byRuleFile.entries()]
    .filter(([k]) => k.startsWith(`${rule}::`))
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([k, c]) => `\`${k.split("::")[1]}\` (${c})`)
    .join(", ");
  lines.push(`| \`${rule}\` | ${count} | ${topFiles} |`);
}
lines.push("");

lines.push("## Top 30 files by count");
lines.push("");
lines.push("| File | Count |");
lines.push("|---|---|");
for (const [file, count] of fileEntries.slice(0, 30)) {
  lines.push(`| \`${file}\` | ${count} |`);
}
lines.push("");

lines.push("## Prioritization guidance for E1c");
lines.push("");
lines.push(
  "Apply fixes in the order of `Top rules by count`. For each rule:",
);
lines.push(
  "1. Check if `eslint --fix` resolves it automatically (some are auto-fixable).",
);
lines.push(
  "2. If not, check if the top-3 files are shared components (`components/ui/*`): a single fix there propagates.",
);
lines.push("3. Otherwise, decide: individual fixes or defer to Phase E2.");
lines.push("");

writeFileSync(OUT_MD, lines.join("\n"), "utf-8");
console.log(`Wrote ${OUT_MD}`);
console.log(
  `Total: ${a11yMessages.length} warnings, ${ruleEntries.length} rules, ${fileEntries.length} files.`,
);

// ── Axe baseline summary (if JSON present) ──────────────────────────────────

const AXE_JSON = path.join(
  PROJECT_ROOT,
  "docs",
  "bug-sweep",
  "a11y-axe-baseline.json",
);
const AXE_MD = path.join(
  PROJECT_ROOT,
  "docs",
  "bug-sweep",
  "a11y-axe-summary.md",
);

if (!existsSync(AXE_JSON)) {
  console.log(`\nAxe baseline not found at ${AXE_JSON} — skipping summary.`);
  console.log(
    "Run the audit first: cd client && npx playwright test e2e/a11y-audit.spec.ts",
  );
  process.exit(0);
}

const axeData = JSON.parse(readFileSync(AXE_JSON, "utf-8"));

// Group by rule across all routes
const axeByRule = new Map();
for (const routeResult of axeData.results) {
  for (const v of routeResult.violations || []) {
    const cur = axeByRule.get(v.id) || {
      count: 0,
      impact: v.impact,
      help: v.help,
      routes: new Set(),
    };
    cur.count += v.nodes;
    cur.routes.add(routeResult.route);
    axeByRule.set(v.id, cur);
  }
}

// Group by impact
const byImpact = {
  critical: 0,
  serious: 0,
  moderate: 0,
  minor: 0,
  unknown: 0,
};
for (const routeResult of axeData.results) {
  for (const v of routeResult.violations || []) {
    const key = v.impact || "unknown";
    byImpact[key] = (byImpact[key] || 0) + v.nodes;
  }
}

const axeLines = [];
axeLines.push(
  `# A11y Axe Baseline Summary — ${axeData.generated_at?.slice(0, 10) || now}`,
);
axeLines.push("");
axeLines.push(
  `Source: \`@axe-core/playwright\` runtime audit via \`client/e2e/a11y-audit.spec.ts\``,
);
axeLines.push(`Raw data: \`docs/bug-sweep/a11y-axe-baseline.json\``);
axeLines.push("");
axeLines.push(`**Total routes audited:** ${axeData.total_routes}`);
axeLines.push(
  `**Routes with errors (non-a11y):** ${axeData.results.filter((r) => r.status === "error").length}`,
);
const allViolations = [...axeByRule.values()].reduce(
  (s, r) => s + r.count,
  0,
);
axeLines.push(`**Total violations (node-level):** ${allViolations}`);
axeLines.push("");
axeLines.push("## Violations by impact");
axeLines.push("");
axeLines.push("| Impact | Count |");
axeLines.push("|---|---|");
for (const [impact, count] of Object.entries(byImpact)) {
  if (count > 0) axeLines.push(`| ${impact} | ${count} |`);
}
axeLines.push("");

axeLines.push("## Top rules by count");
axeLines.push("");
axeLines.push("| Rule | Impact | Count | Routes | Help |");
axeLines.push("|---|---|---|---|---|");
const axeRuleEntries = [...axeByRule.entries()].sort(
  (a, b) => b[1].count - a[1].count,
);
for (const [rule, data] of axeRuleEntries) {
  axeLines.push(
    `| \`${rule}\` | ${data.impact || "unknown"} | ${data.count} | ${data.routes.size} | ${data.help} |`,
  );
}
axeLines.push("");

axeLines.push("## Prioritization guidance for E1c");
axeLines.push("");
axeLines.push(
  "1. **Critical + serious impact affecting > 5 routes**: pattern-level fix in shared components.",
);
axeLines.push(
  "2. **Moderate impact on <= 3 routes**: individual fixes (Phase E2).",
);
axeLines.push("3. **Minor impact**: defer to Phase E3.");
axeLines.push("");
axeLines.push(
  "Cross-reference with `a11y-lint-catalog.md` — when both flag the same component,",
);
axeLines.push("a single fix closes both.");
axeLines.push("");

writeFileSync(AXE_MD, axeLines.join("\n"), "utf-8");
console.log(`\nWrote ${AXE_MD}`);
console.log(
  `Axe summary: ${allViolations} violations across ${axeByRule.size} rules.`,
);
