const ideas = [
  // UX POLISH (15)
  {title:"Global Command Palette (Cmd+K)",description:"Fuzzy-search across all entities (contacts, docs, mails, tasks, containers) with keyboard navigation and instant action dispatch from anywhere in the app.",category:"mediumterm",impact:"high",effort:"2d",tags:["ux","keyboard","search","productivity"]},
  {title:"Keyboard Shortcut System with Cheat Sheet",description:"Register context-aware keyboard shortcuts per module (C to compose, R to reply in mail, N for new task) with a ?-triggered cheat sheet overlay.",category:"quickwin",impact:"medium",effort:"1d",tags:["ux","keyboard","accessibility","productivity"]},
  {title:"Global Drag-and-Drop File Upload Zone",description:"Implement a drag-and-drop zone active on all pages so dropped files auto-route to storage, mail attachments, or doc imports based on current context.",category:"quickwin",impact:"medium",effort:"1d",tags:["ux","drag-drop","storage","uploads"]},
  {title:"Kanban Board View for Scheduler Tasks",description:"Add a drag-and-drop Kanban view to the scheduler service grouping jobs by status (pending/running/failed) with inline card editing.",category:"mediumterm",impact:"medium",effort:"2d",tags:["ux","scheduler","kanban","drag-drop"]},
  {title:"Skeleton Loaders and Animated Page Transitions",description:"Replace blank loading states with layout-matching skeleton placeholders and add subtle fade/slide transitions between routes for a polished feel.",category:"quickwin",impact:"medium",effort:"1d",tags:["ux","animations","loading","polish"]},
  {title:"Onboarding Wizard for First-Time Admin Setup",description:"Multi-step wizard after first login to configure SMTP, LDAP/AD sync, storage backend, and invite users, with progress persisted across refreshes.",category:"mediumterm",impact:"high",effort:"2d",tags:["ux","onboarding","setup","identity"]},
  {title:"Rich Contextual Tooltips on Complex Fields",description:"Add i-icon tooltips on RBAC roles, CIDR ranges, CRON syntax, and VRAM thresholds that show an inline explainer without leaving the page.",category:"quickwin",impact:"medium",effort:"1h",tags:["ux","tooltips","help","accessibility"]},
  {title:"Undo Toast for Destructive Actions",description:"Implement a client-side undo queue for deletions (files, contacts, emails) with a 5-second toast to cancel before the action is committed to the API.",category:"mediumterm",impact:"high",effort:"2d",tags:["ux","undo","safety","toast"]},
  {title:"User Preferences Panel (Theme, Density, Language)",description:"Add a /settings/preferences page for dark/light/system theme, UI density, locale, and default landing page, persisted per user in the identity service.",category:"mediumterm",impact:"medium",effort:"1d",tags:["ux","preferences","theme","i18n"]},
  {title:"Floating Batch Actions Toolbar for List Views",description:"Show a floating action toolbar when multiple rows are selected, offering contextual bulk operations (delete, move, tag, export) without leaving the list.",category:"quickwin",impact:"medium",effort:"1d",tags:["ux","batch","productivity","lists"]},
  {title:"Responsive Mobile Layout for Core Pages",description:"Adapt mail, contacts, calendar, and dashboard to a single-column mobile layout with swipe gestures so the platform is usable on tablets and phones.",category:"mediumterm",impact:"high",effort:"1w",tags:["ux","responsive","mobile","accessibility"]},
  {title:"Inline Rename for Files and Entity Titles",description:"Double-click any entity title (file, doc, contact, CRON job) to enter inline edit mode, saving on Enter/blur without opening a full modal.",category:"quickwin",impact:"medium",effort:"2h",tags:["ux","inline-edit","polish","productivity"]},
  {title:"Pinned / Starred Items Sidebar Section",description:"Let users star any entity (file, contact, doc, container) to pin it in a persistent sidebar section for instant access, stored per user in identity.",category:"quickwin",impact:"medium",effort:"1d",tags:["ux","favorites","sidebar","navigation"]},
  {title:"Distraction-Free Full-Screen Mode for Docs Editor",description:"Add a full-screen writing mode for the docs service that hides the sidebar and header, showing only the document with a minimal floating toolbar.",category:"quickwin",impact:"medium",effort:"2h",tags:["ux","docs","focus","editor"]},
  {title:"WCAG 2.1 AA Accessibility Audit and Fixes",description:"Run automated axe-core scans on all pages and fix contrast ratios, missing ARIA labels, focus traps, and skip-navigation links to reach WCAG 2.1 AA.",category:"mediumterm",impact:"high",effort:"1w",tags:["ux","accessibility","wcag","compliance"]},

  // AI INTEGRATION (10)
  {title:"Smart Compose for Mail (AI Draft Assist)",description:"While composing an email, offer AI sentence completion and full-draft suggestions via the local LLM (signapps-ai), triggered by Tab or a toolbar button.",category:"mediumterm",impact:"high",effort:"2d",tags:["ai","mail","llm","productivity"]},
  {title:"One-Click Document Summarization",description:"Add a Summarize button to any doc or uploaded PDF that calls signapps-ai to generate a 3-5 bullet executive summary in a slide-in panel without modifying the source.",category:"quickwin",impact:"high",effort:"1d",tags:["ai","docs","summarization","llm"]},
  {title:"Meeting Transcription and Auto-Minutes Generator",description:"After a signapps-meet session ends, pipe recorded audio through whisper-rs and auto-generate a timestamped transcript plus action-item list saved to signapps-docs.",category:"longterm",impact:"high",effort:"1w",tags:["ai","meet","stt","transcription","media"]},
  {title:"AI-Powered Contact Deduplication",description:"Use pgvector embeddings on contact names, emails, and phones to detect near-duplicates and surface a Clean Contacts merge workflow as a background job.",category:"mediumterm",impact:"medium",effort:"2d",tags:["ai","contacts","deduplication","pgvector"]},
  {title:"Calendar Scheduling Assistant (Find-a-Slot AI)",description:"AI agent that analyzes attendee calendars and proposes 3 optimal meeting slots with conflict resolution, respecting working-hours preferences stored in identity.",category:"mediumterm",impact:"high",effort:"2d",tags:["ai","calendar","scheduling","llm"]},
  {title:"Contextual RAG Chatbot (Ask About Anything)",description:"Embed a persistent chat widget powered by signapps-ai RAG that answers questions about stored docs, emails, and contacts via pgvector similarity search.",category:"mediumterm",impact:"high",effort:"2d",tags:["ai","chatbot","rag","pgvector","llm"]},
  {title:"AI Anomaly Detection for Metrics Alerts",description:"Train a lightweight statistical model on historical signapps-metrics data to detect CPU/memory/disk anomalies and trigger adaptive smart alerts.",category:"longterm",impact:"high",effort:"1w",tags:["ai","metrics","anomaly-detection","monitoring"]},
  {title:"Auto-Tagging for Files and Emails",description:"On upload or receive, run zero-shot classification via signapps-ai to assign tags (invoice, contract, report) automatically to files and emails.",category:"mediumterm",impact:"medium",effort:"1d",tags:["ai","tagging","storage","mail","llm"]},
  {title:"Smart Reply Chips for Mail",description:"Generate 3 short contextual reply options for any received email using the local LLM, shown as clickable chips above the compose area.",category:"mediumterm",impact:"medium",effort:"1d",tags:["ai","mail","smart-reply","llm"]},
  {title:"Semantic Search with pgvector Re-Ranking",description:"Augment text search with pgvector cosine similarity so queries like 'budget approval Q1' surface semantically related docs even without exact keyword matches.",category:"mediumterm",impact:"high",effort:"2d",tags:["ai","search","pgvector","embeddings","rag"]},

  // COLLABORATION (10)
  {title:"Inline Threaded Comments on Documents",description:"Allow users to select any text range in a doc and leave a threaded comment stored in a comments table linked to entity_id, visible as margin annotations.",category:"mediumterm",impact:"high",effort:"2d",tags:["collaboration","docs","comments","threads"]},
  {title:"@Mentions with Notification Fan-Out",description:"Parse @username mentions in comments, task descriptions, and doc content and trigger in-app and email notifications via signapps-notifications.",category:"mediumterm",impact:"high",effort:"2d",tags:["collaboration","mentions","notifications","identity"]},
  {title:"Shared Workspaces with Permission Inheritance",description:"Create named workspaces grouping docs, files, and tasks under a single ACL so members inherit access to all workspace resources without per-item grants.",category:"longterm",impact:"high",effort:"1w",tags:["collaboration","workspaces","rbac","permissions"]},
  {title:"Real-Time Presence Indicators on Docs and Files",description:"Show avatar bubbles on docs and files currently being viewed or edited by others, broadcasting presence via SSE from signapps-collab with a 30-second TTL.",category:"mediumterm",impact:"medium",effort:"2d",tags:["collaboration","presence","sse","real-time"]},
  {title:"Shared Document Templates Library",description:"Add a Templates section where users can save, share, and instantiate docs from pre-defined templates with per-workspace and global scopes.",category:"mediumterm",impact:"medium",effort:"1d",tags:["collaboration","docs","templates","productivity"]},
  {title:"Team Shared Calendar Overlays",description:"Let users add another user's calendar as a read-only color-coded overlay so teams see collective availability in a single calendar view.",category:"mediumterm",impact:"high",effort:"2d",tags:["collaboration","calendar","teams","scheduling"]},
  {title:"Task Assignment with Due-Date Reminders",description:"Add assignee and due-date fields to scheduler tasks with a team board view and email reminders triggered by signapps-notifications on deadline approach.",category:"mediumterm",impact:"high",effort:"2d",tags:["collaboration","tasks","scheduler","notifications"]},
  {title:"Expiring Password-Protected Share Links",description:"Generate public links for any file or doc via signapps-securelink with configurable expiry, view/download limits, and optional password protection.",category:"quickwin",impact:"high",effort:"1d",tags:["collaboration","sharing","securelink","security"]},
  {title:"Version History and Diff Viewer for Docs",description:"Store doc content snapshots on every save in a doc_versions table and add a side-by-side diff viewer to compare any two versions with author and timestamp.",category:"mediumterm",impact:"high",effort:"2d",tags:["collaboration","docs","versioning","diff"]},
  {title:"Scoped Guest Access Tokens for External Collaborators",description:"Issue time-limited JWT tokens for external users granting read or comment access to specific resources without requiring an account, tracked in the audit log.",category:"longterm",impact:"medium",effort:"2d",tags:["collaboration","guest-access","identity","security"]},

  // DATA & ANALYTICS (10)
  {title:"Storage Quota Dashboard with Per-User Limits",description:"Display per-user and per-workspace storage consumption from signapps-storage with visual quota bars and an admin page to set and enforce limits.",category:"quickwin",impact:"high",effort:"1d",tags:["analytics","storage","quotas","admin"]},
  {title:"Email Delivery Analytics (Send/Bounce/Open Rates)",description:"Track outbound email delivery status, bounce rates, and open tracking from signapps-mail and surface them in a per-domain analytics page.",category:"mediumterm",impact:"medium",effort:"2d",tags:["analytics","mail","tracking","dashboard"]},
  {title:"Calendar Meeting Load Heatmap",description:"Generate a GitHub-style heatmap of meeting hours per day for each user over the past 90 days, highlighting overloaded days for work-life balance insights.",category:"quickwin",impact:"medium",effort:"1d",tags:["analytics","calendar","heatmap","wellbeing"]},
  {title:"Scheduler Job Velocity and Failure Rate Charts",description:"Show a rolling 7/30-day chart of CRON job completion rates, average duration, and failure rates per job type to identify bottlenecks over time.",category:"mediumterm",impact:"medium",effort:"1d",tags:["analytics","scheduler","velocity","charts"]},
  {title:"User Activity Report for Admins",description:"Admin report showing per-user login frequency, last active timestamp, services used, and data created over a configurable date range, exportable to CSV.",category:"mediumterm",impact:"high",effort:"2d",tags:["analytics","admin","reporting","identity"]},
  {title:"Audit Report with Filters and CSV Export",description:"Build an admin audit log viewer with filters by user, action type, service, and date range plus CSV/JSON export, backed by the existing audit_events table.",category:"quickwin",impact:"high",effort:"1d",tags:["analytics","audit","compliance","admin"]},
  {title:"Container Resource Usage Time-Series Charts",description:"Record CPU/memory/network metrics per container every 60 seconds and display sparkline charts per container in the containers management UI.",category:"mediumterm",impact:"medium",effort:"2d",tags:["analytics","containers","metrics","time-series"]},
  {title:"AI Inference Usage and Compute Cost Tracker",description:"Log every LLM/STT/TTS inference call with token counts, model name, duration, and estimated compute cost, displayed in a per-user usage dashboard.",category:"mediumterm",impact:"medium",effort:"1d",tags:["analytics","ai","cost-tracking","metrics"]},
  {title:"Storage File Type Distribution Donut Chart",description:"Show a donut chart of files by MIME type and a 30-day upload trend by category in the storage analytics page to understand growth patterns.",category:"quickwin",impact:"low",effort:"2h",tags:["analytics","storage","charts","dashboard"]},
  {title:"GDPR Compliance Dashboard (PII Inventory and Retention)",description:"Surface PII data inventory, data retention age, and pending deletion requests in a dedicated compliance page linked to PII encryption and audit log.",category:"longterm",impact:"high",effort:"1w",tags:["analytics","compliance","gdpr","privacy","audit"]},

  // DEVELOPER EXPERIENCE (10)
  {title:"utoipa OpenAPI 3.1 Spec Auto-Generation per Service",description:"Integrate utoipa into each Rust service to derive an OpenAPI 3.1 spec from handler annotations, served at /api/v1/openapi.json for tooling and SDK generation.",category:"mediumterm",impact:"high",effort:"2d",tags:["dx","openapi","rust","documentation"]},
  {title:"Scalar API Playground Mounted per Service",description:"Mount a Scalar UI at /docs on each service gated by admin role so developers can explore and test endpoints interactively without external tooling.",category:"quickwin",impact:"medium",effort:"1d",tags:["dx","openapi","swagger","api-playground"]},
  {title:"Webhook Management UI with Delivery Logs",description:"UI page to register, test, and inspect outbound webhook subscriptions for key events (file uploaded, contact created, job failed) with delivery logs and retry controls.",category:"mediumterm",impact:"high",effort:"2d",tags:["dx","webhooks","integrations","events"]},
  {title:"TypeScript SDK Auto-Generation from OpenAPI Specs",description:"Add a npm script running openapi-typescript against each service spec to generate typed client SDKs in client/src/lib/sdk/, replacing hand-written axios calls over time.",category:"mediumterm",impact:"medium",effort:"1d",tags:["dx","sdk","typescript","codegen","openapi"]},
  {title:"Centralized Log Viewer in Admin UI (SSE Streaming)",description:"Add a /admin/logs page streaming log lines from all signapps-*.log files via SSE, with per-service toggles, severity filter, and text search.",category:"mediumterm",impact:"high",effort:"2d",tags:["dx","logging","admin","sse","monitoring"]},
  {title:"Database Migration Status Page",description:"Display all applied and pending sqlx migrations per service with timestamps and checksums, plus a one-click run-pending button for admin use.",category:"quickwin",impact:"medium",effort:"1d",tags:["dx","migrations","admin","sqlx","database"]},
  {title:"Rust pprof Flamegraph Profiling Endpoint",description:"Add an optional /debug/profile endpoint feature-flagged to each service that captures a 30-second flamegraph via pprof-rs and returns it for download.",category:"longterm",impact:"medium",effort:"2d",tags:["dx","performance","profiling","rust","debugging"]},
  {title:"Environment Config Diff CLI Tool",description:"Script that compares .env files across environments, highlights missing keys and value mismatches, and warns on secrets accidentally set to dev defaults.",category:"quickwin",impact:"medium",effort:"2h",tags:["dx","config","security","tooling","cli"]},
  {title:"Local Feature Flag System",description:"Implement a feature_flags table in PostgreSQL with per-user and per-role overrides, exposed via a /api/v1/flags endpoint and a React hook for frontend gating.",category:"mediumterm",impact:"medium",effort:"1d",tags:["dx","feature-flags","identity","rollout"]},
  {title:"cargo-audit and npm-audit CVE Dashboard",description:"Add cargo-audit and npm-audit to CI with a daily scheduled run and an admin dashboard panel showing known CVEs with severity badges and fix guidance.",category:"quickwin",impact:"high",effort:"1h",tags:["dx","security","cargo-audit","ci","vulnerabilities"]},

  // PERFORMANCE (5)
  {title:"Virtual Scrolling for Large Entity Lists",description:"Replace paginated email/contact/file lists with @tanstack/react-virtual infinite scroll so the DOM stays bounded and performs well with 10k+ items.",category:"mediumterm",impact:"high",effort:"2d",tags:["performance","virtual-scroll","frontend","lists"]},
  {title:"Immutable Cache-Control Headers on Static Assets",description:"Configure signapps-proxy to add Cache-Control: immutable with content-hash cache busting on all Next.js static chunks, reducing repeat load times drastically.",category:"quickwin",impact:"medium",effort:"30min",tags:["performance","caching","proxy","frontend"]},
  {title:"Lazy-Load Heavy Page Modules (Meet, Office, Media)",description:"Convert signapps-meet, signapps-office, and signapps-media page imports to Next.js dynamic() with suspense so the initial JS bundle excludes these heavy modules.",category:"quickwin",impact:"medium",effort:"1h",tags:["performance","lazy-loading","next-js","bundle-size"]},
  {title:"Image Optimization Pipeline via signapps-media",description:"Route uploaded images through signapps-media to auto-generate WebP/AVIF variants at multiple resolutions, served via Next.js Image component with srcset.",category:"mediumterm",impact:"medium",effort:"2d",tags:["performance","images","media","optimization"]},
  {title:"N+1 Query Elimination with Batch Fetch Pattern",description:"Audit the repository layer for N+1 queries in list endpoints and replace with IN-clause batching or CTEs to reduce list API response times by up to 10x.",category:"mediumterm",impact:"high",effort:"2d",tags:["performance","database","n+1","sqlx","rust"]}
];

console.log(JSON.stringify(ideas, null, 2));
