use rust_xlsxwriter::Workbook;

pub fn generate_xlsx() -> Result<Vec<u8>, rust_xlsxwriter::XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();
    
    worksheet.write_string(0, 0, "Generated by signapps-office")?;
    
    // Save workbook to buffer
    workbook.save_to_buffer()
}
