//! Generated media models for AI-produced images, audio, and video.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// A media asset generated by an AI model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedMedia {
    pub id: Uuid,
    pub media_type: String,
    pub prompt: String,
    pub model_used: String,
    pub storage_path: String,
    pub file_size_bytes: Option<i64>,
    pub metadata: Option<serde_json::Value>,
    pub indexed: bool,
    pub conversation_id: Option<Uuid>,
    pub user_id: Uuid,
    pub created_at: DateTime<Utc>,
}
