"use client";

/**
 * TimesheetView Component
 *
 * Weekly timesheet view for the current user.
 * Allows editing hours per category per day, auto-generation from events,
 * validation, and export.
 */

import React, {
  useState,
  useEffect,
  useCallback,
  useRef,
  useMemo,
} from "react";
import {
  format,
  startOfWeek,
  endOfWeek,
  addWeeks,
  subWeeks,
  getWeek,
  getISOWeek,
  getYear,
  parseISO,
  addDays,
  isToday,
} from "date-fns";
import { fr } from "date-fns/locale";
import {
  ChevronLeft,
  ChevronRight,
  Bot,
  CheckCircle,
  Clock,
  Download,
  Zap,
  Save,
  RefreshCw,
  AlertCircle,
  Info,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";
import { timesheetsApi, categoriesApi } from "@/lib/api/calendar";
import { TimesheetExportDialog } from "./TimesheetExportDialog";

// ============================================================================
// Types
// ============================================================================

type TimesheetStatus = "pending" | "validated" | "exported";

interface TimesheetCategory {
  id: string;
  name: string;
  color?: string;
}

interface DayEntry {
  hours: number;
  autoGenerated: boolean;
  modified: boolean;
  entryId?: string;
}

interface CategoryRow {
  category: TimesheetCategory;
  dayEntries: Record<string, DayEntry>; // ISO date (YYYY-MM-DD) -> entry
}

interface TimesheetData {
  id?: string;
  week: string; // e.g. "2026-W13"
  status: TimesheetStatus;
  generatedAt?: string;
  validatedAt?: string;
  exportedAt?: string;
  rows: CategoryRow[];
}

// ============================================================================
// Helpers
// ============================================================================

const DAYS_OF_WEEK = ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"];

function getWeekKey(date: Date): string {
  const year = getYear(startOfWeek(date, { weekStartsOn: 1 }));
  const week = getISOWeek(date);
  return `${year}-W${String(week).padStart(2, "0")}`;
}

function getWeekDays(date: Date): Date[] {
  const start = startOfWeek(date, { weekStartsOn: 1 });
  return Array.from({ length: 7 }, (_, i) => addDays(start, i));
}

function formatHours(h: number): string {
  if (h === 0) return "—";
  return h % 1 === 0 ? `${h}h` : `${h.toFixed(1)}h`;
}

function sumRow(row: CategoryRow, days: Date[]): number {
  return days.reduce((acc, d) => {
    const key = format(d, "yyyy-MM-dd");
    return acc + (row.dayEntries[key]?.hours ?? 0);
  }, 0);
}

function sumDay(rows: CategoryRow[], dateKey: string): number {
  return rows.reduce(
    (acc, row) => acc + (row.dayEntries[dateKey]?.hours ?? 0),
    0
  );
}

function sumTotal(rows: CategoryRow[], days: Date[]): number {
  return days.reduce((acc, d) => {
    const key = format(d, "yyyy-MM-dd");
    return acc + sumDay(rows, key);
  }, 0);
}

const DEFAULT_CATEGORIES: TimesheetCategory[] = [
  { id: "normal", name: "Heures normales", color: "#3b82f6" },
  { id: "formation", name: "Formation", color: "#8b5cf6" },
  { id: "astreinte", name: "Astreinte", color: "#f59e0b" },
  { id: "deplacement", name: "Déplacement", color: "#10b981" },
  { id: "reunion", name: "Réunion", color: "#ec4899" },
];

function buildEmptyRow(
  category: TimesheetCategory,
  days: Date[]
): CategoryRow {
  const dayEntries: Record<string, DayEntry> = {};
  days.forEach((d) => {
    dayEntries[format(d, "yyyy-MM-dd")] = {
      hours: 0,
      autoGenerated: false,
      modified: false,
    };
  });
  return { category, dayEntries };
}

// Merge API data into rows structure
function mergeApiEntries(
  rows: CategoryRow[],
  apiEntries: any[],
  days: Date[]
): CategoryRow[] {
  const merged = rows.map((row) => ({
    ...row,
    dayEntries: { ...row.dayEntries },
  }));

  apiEntries.forEach((entry: any) => {
    const dateKey = entry.date
      ? format(parseISO(entry.date), "yyyy-MM-dd")
      : null;
    if (!dateKey) return;
    const rowIdx = merged.findIndex(
      (r) =>
        r.category.id === entry.category_id ||
        r.category.name === entry.category
    );
    if (rowIdx >= 0) {
      merged[rowIdx].dayEntries[dateKey] = {
        hours: entry.hours ?? 0,
        autoGenerated: entry.auto_generated ?? false,
        modified: false,
        entryId: entry.id,
      };
    }
  });

  return merged;
}

// ============================================================================
// Editable Cell
// ============================================================================

interface EditableCellProps {
  value: number;
  autoGenerated: boolean;
  modified: boolean;
  isToday: boolean;
  onChange: (val: number) => void;
  disabled: boolean;
}

function EditableCell({
  value,
  autoGenerated,
  modified,
  isToday: isTodayDay,
  onChange,
  disabled,
}: EditableCellProps) {
  const [editing, setEditing] = useState(false);
  const [raw, setRaw] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const handleDoubleClick = () => {
    if (disabled) return;
    setRaw(value === 0 ? "" : String(value));
    setEditing(true);
  };

  useEffect(() => {
    if (editing && inputRef.current) {
      inputRef.current.focus();
      inputRef.current.select();
    }
  }, [editing]);

  const commit = () => {
    const parsed = parseFloat(raw.replace(",", "."));
    const next = isNaN(parsed) ? 0 : Math.max(0, Math.min(24, parsed));
    onChange(next);
    setEditing(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" || e.key === "Tab") commit();
    if (e.key === "Escape") setEditing(false);
  };

  if (editing) {
    return (
      <td className="px-1 py-1 text-center w-[80px]">
        <Input
          ref={inputRef}
          value={raw}
          onChange={(e) => setRaw(e.target.value)}
          onBlur={commit}
          onKeyDown={handleKeyDown}
          className="h-7 w-16 text-center text-sm mx-auto"
          placeholder="0"
        />
      </td>
    );
  }

  return (
    <td
      onDoubleClick={handleDoubleClick}
      className={cn(
        "px-2 py-2 text-center text-sm w-[80px] select-none transition-colors",
        "group cursor-default",
        !disabled && "hover:bg-muted/40 hover:cursor-pointer",
        isTodayDay && "bg-primary/5",
        modified && "bg-yellow-500/10 dark:bg-yellow-400/10",
        value > 0 && !modified && "text-foreground",
        value === 0 && "text-muted-foreground/50"
      )}
      title={disabled ? undefined : "Double-clic pour modifier"}
    >
      <span className="flex items-center justify-center gap-1">
        {autoGenerated && value > 0 && (
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Bot className="h-3 w-3 text-primary/60 shrink-0" />
              </TooltipTrigger>
              <TooltipContent side="top">
                <p>Généré automatiquement</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        )}
        {value === 0 ? "—" : formatHours(value)}
      </span>
    </td>
  );
}

// ============================================================================
// Status Badge
// ============================================================================

function StatusBadge({ status }: { status: TimesheetStatus }) {
  if (status === "validated") {
    return (
      <Badge className="gap-1 bg-green-500/15 text-green-700 dark:text-green-400 border-green-500/30 hover:bg-green-500/20">
        <CheckCircle className="h-3 w-3" />
        Validé
      </Badge>
    );
  }
  if (status === "exported") {
    return (
      <Badge className="gap-1 bg-blue-500/15 text-blue-700 dark:text-blue-400 border-blue-500/30 hover:bg-blue-500/20">
        <Download className="h-3 w-3" />
        Exporté
      </Badge>
    );
  }
  return (
    <Badge className="gap-1 bg-orange-500/15 text-orange-700 dark:text-orange-400 border-orange-500/30 hover:bg-orange-500/20">
      <Clock className="h-3 w-3" />
      Non validé
    </Badge>
  );
}

// ============================================================================
// Main Component
// ============================================================================

export function TimesheetView() {
  const [currentDate, setCurrentDate] = useState(() => new Date());
  const [timesheetData, setTimesheetData] = useState<TimesheetData | null>(
    null
  );
  const [categories, setCategories] = useState<TimesheetCategory[]>(
    DEFAULT_CATEGORIES
  );
  const [rows, setRows] = useState<CategoryRow[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isValidating, setIsValidating] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [successMsg, setSuccessMsg] = useState<string | null>(null);
  const [exportDialogOpen, setExportDialogOpen] = useState(false);
  const [hasUnsaved, setHasUnsaved] = useState(false);

  const weekKey = useMemo(() => getWeekKey(currentDate), [currentDate]);
  const weekDays = useMemo(() => getWeekDays(currentDate), [currentDate]);
  const weekNumber = useMemo(
    () => getISOWeek(currentDate),
    [currentDate]
  );

  // Load categories
  useEffect(() => {
    categoriesApi
      .list()
      .then((res: any) => {
        const data = res.data;
        if (Array.isArray(data) && data.length > 0) {
          setCategories(
            data.map((c: any) => ({
              id: c.id,
              name: c.name,
              color: c.color,
            }))
          );
        }
      })
      .catch(() => {
        // Fall back to defaults silently
      });
  }, []);

  // Load timesheet data for the current week
  const loadTimesheet = useCallback(
    async (cats: TimesheetCategory[], days: Date[]) => {
      setIsLoading(true);
      setError(null);

      const emptyRows = cats.map((c) => buildEmptyRow(c, days));

      try {
        const res = await timesheetsApi.list({ week: weekKey });
        const data: any = res.data;

        let status: TimesheetStatus = "pending";
        let id: string | undefined;
        let generatedAt: string | undefined;
        let validatedAt: string | undefined;
        let exportedAt: string | undefined;
        let entries: any[] = [];

        if (Array.isArray(data)) {
          // List of entries
          entries = data;
          const validated = data.some((e: any) => e.status === "validated");
          const exported = data.some((e: any) => e.status === "exported");
          status = exported ? "exported" : validated ? "validated" : "pending";
          generatedAt = data[0]?.generated_at;
          validatedAt = data[0]?.validated_at;
          exportedAt = data[0]?.exported_at;
          id = data[0]?.timesheet_id;
        } else if (data && typeof data === "object") {
          // Single timesheet object
          status = data.status ?? "pending";
          id = data.id;
          generatedAt = data.generated_at;
          validatedAt = data.validated_at;
          exportedAt = data.exported_at;
          entries = data.entries ?? [];
        }

        const mergedRows = mergeApiEntries(emptyRows, entries, days);
        setRows(mergedRows);
        setTimesheetData({
          id,
          week: weekKey,
          status,
          generatedAt,
          validatedAt,
          exportedAt,
          rows: mergedRows,
        });
        setHasUnsaved(false);
      } catch {
        // No data yet for this week — show empty grid
        setRows(emptyRows);
        setTimesheetData({
          week: weekKey,
          status: "pending",
          rows: emptyRows,
        });
        setHasUnsaved(false);
      } finally {
        setIsLoading(false);
      }
    },
    [weekKey]
  );

  useEffect(() => {
    loadTimesheet(categories, weekDays);
  }, [weekKey, categories.length]); // eslint-disable-line react-hooks/exhaustive-deps

  // Navigate weeks
  const goPrev = () => setCurrentDate((d) => subWeeks(d, 1));
  const goNext = () => setCurrentDate((d) => addWeeks(d, 1));

  // Auto-generate from events
  const handleGenerate = async () => {
    setIsGenerating(true);
    setError(null);
    try {
      const start = format(weekDays[0], "yyyy-MM-dd");
      const end = format(weekDays[6], "yyyy-MM-dd");
      await timesheetsApi.generate(start, end);
      showSuccess("Feuille de temps générée depuis les événements.");
      await loadTimesheet(categories, weekDays);
    } catch (err: any) {
      setError(
        err?.response?.data?.message ??
          err?.message ??
          "Erreur lors de la génération."
      );
    } finally {
      setIsGenerating(false);
    }
  };

  // Validate the week
  const handleValidate = async () => {
    setIsValidating(true);
    setError(null);
    try {
      await timesheetsApi.validate(weekKey);
      setTimesheetData((prev) =>
        prev
          ? { ...prev, status: "validated", validatedAt: new Date().toISOString() }
          : prev
      );
      showSuccess("Semaine validée avec succès.");
    } catch (err: any) {
      setError(
        err?.response?.data?.message ??
          err?.message ??
          "Erreur lors de la validation."
      );
    } finally {
      setIsValidating(false);
    }
  };

  // Save modified cells
  const handleSave = async () => {
    if (!hasUnsaved) return;
    setIsSaving(true);
    setError(null);
    try {
      const updates: Array<{ date: string; category_id: string; hours: number }> =
        [];
      rows.forEach((row) => {
        weekDays.forEach((d) => {
          const key = format(d, "yyyy-MM-dd");
          const entry = row.dayEntries[key];
          if (entry?.modified) {
            updates.push({
              date: key,
              category_id: row.category.id,
              hours: entry.hours,
            });
          }
        });
      });

      // Batch update via timesheet API
      if (timesheetData?.id) {
        await timesheetsApi.update(timesheetData.id, {
          week: weekKey,
          entries: updates,
        });
      } else {
        // Try to update by week key
        await timesheetsApi.update("current", {
          week: weekKey,
          entries: updates,
        });
      }

      // Mark all as saved
      setRows((prev) =>
        prev.map((row) => ({
          ...row,
          dayEntries: Object.fromEntries(
            Object.entries(row.dayEntries).map(([k, v]) => [
              k,
              { ...v, modified: false },
            ])
          ),
        }))
      );
      setHasUnsaved(false);
      showSuccess("Modifications sauvegardées.");
    } catch (err: any) {
      setError(
        err?.response?.data?.message ??
          err?.message ??
          "Erreur lors de la sauvegarde."
      );
    } finally {
      setIsSaving(false);
    }
  };

  // Cell value change handler
  const handleCellChange = useCallback(
    (rowIdx: number, dateKey: string, newHours: number) => {
      setRows((prev) => {
        const next = prev.map((row, i) => {
          if (i !== rowIdx) return row;
          return {
            ...row,
            dayEntries: {
              ...row.dayEntries,
              [dateKey]: {
                ...row.dayEntries[dateKey],
                hours: newHours,
                modified: true,
              },
            },
          };
        });
        return next;
      });
      setHasUnsaved(true);
    },
    []
  );

  function showSuccess(msg: string) {
    setSuccessMsg(msg);
    setTimeout(() => setSuccessMsg(null), 3000);
  }

  const isReadOnly =
    timesheetData?.status === "validated" ||
    timesheetData?.status === "exported";

  const totalByDay = useMemo(
    () =>
      weekDays.map((d) => ({
        dateKey: format(d, "yyyy-MM-dd"),
        total: sumDay(rows, format(d, "yyyy-MM-dd")),
      })),
    [rows, weekDays]
  );

  const grandTotal = useMemo(
    () => sumTotal(rows, weekDays),
    [rows, weekDays]
  );

  // ============================================================================
  // Render
  // ============================================================================

  return (
    <div className="flex flex-col h-full bg-background">
      {/* ── Header ────────────────────────────────────────────────────────── */}
      <div className="flex flex-col gap-3 px-4 py-3 border-b bg-card">
        <div className="flex items-center justify-between gap-4 flex-wrap">
          {/* Week selector */}
          <div className="flex items-center gap-2">
            <Button
              variant="outline"
              size="icon"
              onClick={goPrev}
              className="h-8 w-8"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>

            <div className="min-w-[160px] text-center">
              <p className="font-semibold text-sm">
                Semaine {weekNumber}
              </p>
              <p className="text-xs text-muted-foreground">
                {format(weekDays[0], "d MMM", { locale: fr })} –{" "}
                {format(weekDays[6], "d MMM yyyy", { locale: fr })}
              </p>
            </div>

            <Button
              variant="outline"
              size="icon"
              onClick={goNext}
              className="h-8 w-8"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>

          {/* Status */}
          {timesheetData && <StatusBadge status={timesheetData.status} />}

          {/* Actions */}
          <div className="flex items-center gap-2 ml-auto">
            {hasUnsaved && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleSave}
                disabled={isSaving}
                className="gap-1.5 text-yellow-700 dark:text-yellow-400 border-yellow-500/40 hover:bg-yellow-500/10"
              >
                {isSaving ? (
                  <RefreshCw className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <Save className="h-3.5 w-3.5" />
                )}
                Sauvegarder
              </Button>
            )}

            <Button
              variant="outline"
              size="sm"
              onClick={handleGenerate}
              disabled={isGenerating || isReadOnly}
              className="gap-1.5"
            >
              {isGenerating ? (
                <RefreshCw className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <Zap className="h-3.5 w-3.5" />
              )}
              Générer
            </Button>

            <Button
              size="sm"
              onClick={handleValidate}
              disabled={
                isValidating ||
                isReadOnly ||
                grandTotal === 0
              }
              className="gap-1.5"
            >
              {isValidating ? (
                <RefreshCw className="h-3.5 w-3.5 animate-spin" />
              ) : (
                <CheckCircle className="h-3.5 w-3.5" />
              )}
              Valider la semaine
            </Button>

            <Button
              variant="outline"
              size="sm"
              onClick={() => setExportDialogOpen(true)}
              className="gap-1.5"
            >
              <Download className="h-3.5 w-3.5" />
              Exporter
            </Button>
          </div>
        </div>

        {/* Notifications */}
        {error && (
          <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-destructive/10 text-destructive text-sm">
            <AlertCircle className="h-4 w-4 shrink-0" />
            {error}
          </div>
        )}
        {successMsg && (
          <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-green-500/10 text-green-700 dark:text-green-400 text-sm">
            <CheckCircle className="h-4 w-4 shrink-0" />
            {successMsg}
          </div>
        )}
        {isReadOnly && (
          <div className="flex items-center gap-2 px-3 py-2 rounded-md bg-muted text-muted-foreground text-sm">
            <Info className="h-4 w-4 shrink-0" />
            Cette semaine est{" "}
            {timesheetData?.status === "exported" ? "exportée" : "validée"} —
            lecture seule.
          </div>
        )}
      </div>

      {/* ── Table ─────────────────────────────────────────────────────────── */}
      <div className="flex-1 overflow-auto">
        {isLoading ? (
          <div className="flex items-center justify-center h-48 text-muted-foreground gap-2">
            <RefreshCw className="h-5 w-5 animate-spin" />
            Chargement…
          </div>
        ) : (
          <table className="w-full border-collapse text-sm min-w-[700px]">
            <thead className="sticky top-0 z-10 bg-card border-b">
              <tr>
                {/* Category column */}
                <th className="text-left px-4 py-3 font-medium text-muted-foreground w-[180px] min-w-[140px]">
                  Catégorie
                </th>

                {/* Day columns */}
                {weekDays.map((day, i) => {
                  const todayDay = isToday(day);
                  return (
                    <th
                      key={i}
                      className={cn(
                        "text-center px-2 py-3 font-medium text-muted-foreground w-[80px]",
                        todayDay &&
                          "text-primary font-semibold"
                      )}
                    >
                      <div>{DAYS_OF_WEEK[i]}</div>
                      <div
                        className={cn(
                          "text-xs font-normal",
                          todayDay
                            ? "text-primary"
                            : "text-muted-foreground/70"
                        )}
                      >
                        {format(day, "d MMM", { locale: fr })}
                      </div>
                    </th>
                  );
                })}

                {/* Total column */}
                <th className="text-center px-3 py-3 font-medium text-muted-foreground w-[80px]">
                  Total
                </th>
              </tr>
            </thead>

            <tbody>
              {rows.map((row, rowIdx) => {
                const rowTotal = sumRow(row, weekDays);
                const hasData = rowTotal > 0;

                return (
                  <tr
                    key={row.category.id}
                    className={cn(
                      "border-b transition-colors",
                      "hover:bg-muted/30",
                      !hasData && "opacity-60"
                    )}
                  >
                    {/* Category label */}
                    <td className="px-4 py-2">
                      <div className="flex items-center gap-2">
                        {row.category.color && (
                          <span
                            className="inline-block h-2.5 w-2.5 rounded-full shrink-0"
                            style={{ backgroundColor: row.category.color }}
                          />
                        )}
                        <span
                          className={cn(
                            "text-sm",
                            hasData
                              ? "text-foreground font-medium"
                              : "text-muted-foreground"
                          )}
                        >
                          {row.category.name}
                        </span>
                      </div>
                    </td>

                    {/* Day cells */}
                    {weekDays.map((day) => {
                      const dateKey = format(day, "yyyy-MM-dd");
                      const entry = row.dayEntries[dateKey] ?? {
                        hours: 0,
                        autoGenerated: false,
                        modified: false,
                      };
                      return (
                        <EditableCell
                          key={dateKey}
                          value={entry.hours}
                          autoGenerated={entry.autoGenerated}
                          modified={entry.modified}
                          isToday={isToday(day)}
                          onChange={(val) =>
                            handleCellChange(rowIdx, dateKey, val)
                          }
                          disabled={isReadOnly}
                        />
                      );
                    })}

                    {/* Row total */}
                    <td
                      className={cn(
                        "text-center px-3 py-2 font-medium text-sm",
                        hasData
                          ? "text-foreground"
                          : "text-muted-foreground/50"
                      )}
                    >
                      {rowTotal === 0 ? "—" : formatHours(rowTotal)}
                    </td>
                  </tr>
                );
              })}

              {/* ── Total row ─────────────────────────────────────────── */}
              <tr className="bg-muted/40 border-t-2 border-border font-semibold">
                <td className="px-4 py-3 text-sm font-bold">Total</td>

                {weekDays.map((day) => {
                  const dateKey = format(day, "yyyy-MM-dd");
                  const dayTotal = sumDay(rows, dateKey);
                  const todayDay = isToday(day);
                  return (
                    <td
                      key={dateKey}
                      className={cn(
                        "text-center px-2 py-3 text-sm font-bold",
                        todayDay && "text-primary",
                        dayTotal === 0 && "text-muted-foreground/50 font-normal"
                      )}
                    >
                      {dayTotal === 0 ? "—" : formatHours(dayTotal)}
                    </td>
                  );
                })}

                <td className="text-center px-3 py-3 text-sm font-bold text-primary">
                  {formatHours(grandTotal)}
                </td>
              </tr>
            </tbody>
          </table>
        )}
      </div>

      {/* ── Footer ────────────────────────────────────────────────────────── */}
      <div className="border-t bg-card px-4 py-3">
        <div className="flex items-center justify-between flex-wrap gap-3 text-xs text-muted-foreground">
          <div className="flex items-center gap-4 flex-wrap">
            {timesheetData?.generatedAt && (
              <span className="flex items-center gap-1">
                <Bot className="h-3.5 w-3.5 text-primary/60" />
                Généré le{" "}
                {format(parseISO(timesheetData.generatedAt), "d MMM yyyy à HH:mm", {
                  locale: fr,
                })}
              </span>
            )}
            {timesheetData?.validatedAt && (
              <span className="flex items-center gap-1">
                <CheckCircle className="h-3.5 w-3.5 text-green-500" />
                Validé le{" "}
                {format(
                  parseISO(timesheetData.validatedAt),
                  "d MMM yyyy à HH:mm",
                  { locale: fr }
                )}
              </span>
            )}
            {timesheetData?.exportedAt && (
              <span className="flex items-center gap-1">
                <Download className="h-3.5 w-3.5 text-blue-500" />
                Exporté le{" "}
                {format(
                  parseISO(timesheetData.exportedAt),
                  "d MMM yyyy à HH:mm",
                  { locale: fr }
                )}
              </span>
            )}
          </div>

          <div className="flex items-center gap-4">
            <span>
              {grandTotal > 0
                ? `${formatHours(grandTotal)} / semaine`
                : "Aucune heure saisie"}
            </span>
            {hasUnsaved && (
              <span className="text-yellow-600 dark:text-yellow-400 font-medium">
                · Modifications non sauvegardées
              </span>
            )}
          </div>
        </div>

        {/* Legend */}
        <div className="flex items-center gap-4 mt-2 pt-2 border-t border-border/50">
          <span className="flex items-center gap-1 text-xs text-muted-foreground">
            <Bot className="h-3 w-3 text-primary/60" />
            Généré automatiquement
          </span>
          <span className="flex items-center gap-1 text-xs text-muted-foreground">
            <span className="inline-block h-3 w-3 rounded-sm bg-yellow-400/30 border border-yellow-500/40" />
            Modifié non sauvegardé
          </span>
          <span className="text-xs text-muted-foreground">
            Double-clic sur une cellule pour modifier
          </span>
        </div>
      </div>

      {/* ── Export Dialog ─────────────────────────────────────────────────── */}
      <TimesheetExportDialog
        open={exportDialogOpen}
        onOpenChange={setExportDialogOpen}
        defaultStartDate={format(weekDays[0], "yyyy-MM-dd")}
        defaultEndDate={format(weekDays[6], "yyyy-MM-dd")}
      />
    </div>
  );
}

export default TimesheetView;
