#!/usr/bin/env node
/**
 * Backend Coverage Catalog Generator — Phase F1
 *
 * Parses lcov.info (produced by `just coverage`) into a markdown
 * catalog grouped by workspace member, with a top-N low-coverage
 * files section.
 *
 * Usage:
 *   cd /c/Prog/signapps-platform
 *   just coverage
 *   node tools/coverage-catalog.mjs
 *
 * Output: docs/bug-sweep/coverage-catalog.md
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";

// Path resolution (Windows-safe)

const SCRIPT_DIR_RAW = path.dirname(new URL(import.meta.url).pathname);
const SCRIPT_DIR =
  SCRIPT_DIR_RAW.startsWith("/") && /^\/[A-Za-z]:/.test(SCRIPT_DIR_RAW)
    ? SCRIPT_DIR_RAW.slice(1)
    : SCRIPT_DIR_RAW;
const PROJECT_ROOT = path.resolve(SCRIPT_DIR, "..");
const LCOV = path.join(PROJECT_ROOT, "lcov.info");
const OUT = path.join(PROJECT_ROOT, "docs", "bug-sweep", "coverage-catalog.md");

if (!existsSync(LCOV)) {
  console.error(`lcov.info not found at ${LCOV}`);
  console.error("Run: just coverage");
  process.exit(1);
}

// Parse lcov records
// Format per record:
//   SF:path/to/file.rs
//   DA:lineNum,hitCount
//   LF:<totalLines>
//   LH:<hitLines>
//   end_of_record

const raw = readFileSync(LCOV, "utf-8");
const records = raw.split("end_of_record").filter((r) => r.trim());

const fileStats = [];
for (const record of records) {
  const sfMatch = /^SF:(.+)$/m.exec(record);
  if (!sfMatch) continue;
  const file = sfMatch[1].trim();

  const lfMatch = /^LF:(\d+)$/m.exec(record);
  const lhMatch = /^LH:(\d+)$/m.exec(record);
  if (!lfMatch || !lhMatch) continue;

  fileStats.push({
    file: path.relative(PROJECT_ROOT, file).replace(/\\/g, "/"),
    totalLines: parseInt(lfMatch[1], 10),
    hitLines: parseInt(lhMatch[1], 10),
  });
}

// Aggregate by workspace member

function memberFor(file) {
  const m = /^(crates|services|tools|src-tauri)\/([^/]+)\//.exec(file);
  if (!m) return "<other>";
  return m[2];
}

const byMember = new Map();
for (const s of fileStats) {
  const member = memberFor(s.file);
  const cur = byMember.get(member) || {
    name: member,
    files: 0,
    totalLines: 0,
    hitLines: 0,
  };
  cur.files += 1;
  cur.totalLines += s.totalLines;
  cur.hitLines += s.hitLines;
  byMember.set(member, cur);
}

const memberEntries = [...byMember.values()]
  .map((m) => ({
    ...m,
    coverage: m.totalLines > 0 ? (m.hitLines / m.totalLines) * 100 : 0,
  }))
  .sort((a, b) => a.coverage - b.coverage);

// Top-N lowest-coverage files (with totalLines >= 20 to filter tiny modules)

const fileCov = fileStats
  .map((s) => ({
    ...s,
    coverage: s.totalLines > 0 ? (s.hitLines / s.totalLines) * 100 : 0,
  }))
  .filter((s) => s.totalLines >= 20)
  .sort((a, b) => a.coverage - b.coverage);

// Security/crypto hot spots heuristic

const SECURITY_KEYWORDS = [
  "auth",
  "jwt",
  "password",
  "crypto",
  "keystore",
  "hmac",
  "rate",
  "acl",
  "permission",
  "middleware",
];

const hotSpots = fileCov
  .filter((s) => {
    const lower = s.file.toLowerCase();
    return SECURITY_KEYWORDS.some((k) => lower.includes(k)) && s.coverage < 60;
  })
  .slice(0, 15);

// Global totals

const globalTotal = fileStats.reduce((a, s) => a + s.totalLines, 0);
const globalHit = fileStats.reduce((a, s) => a + s.hitLines, 0);
const globalPct = globalTotal > 0 ? (globalHit / globalTotal) * 100 : 0;

// Emit markdown

const now = new Date().toISOString().slice(0, 10);
const lines = [];
lines.push(`# Backend Coverage Catalog — ${now}`);
lines.push("");
lines.push(
  `Source: \`lcov.info\` generated by \`cargo llvm-cov --workspace --lcov\``,
);
lines.push(`Script: \`tools/coverage-catalog.mjs\``);
lines.push("");
lines.push(`**Total lines:** ${globalTotal.toLocaleString()}`);
lines.push(`**Covered lines:** ${globalHit.toLocaleString()}`);
lines.push(`**Workspace coverage:** ${globalPct.toFixed(2)}%`);
lines.push(`**Files:** ${fileStats.length}`);
lines.push(`**Workspace members:** ${memberEntries.length}`);
lines.push("");

lines.push("## Members by coverage (ascending)");
lines.push("");
lines.push("| Member | Files | Lines | Covered | Coverage |");
lines.push("|---|---|---|---|---|");
for (const m of memberEntries) {
  lines.push(
    `| \`${m.name}\` | ${m.files} | ${m.totalLines} | ${m.hitLines} | ${m.coverage.toFixed(1)}% |`,
  );
}
lines.push("");

lines.push("## Top 20 lowest-coverage files (>= 20 lines)");
lines.push("");
lines.push("| File | Lines | Covered | Coverage |");
lines.push("|---|---|---|---|");
for (const f of fileCov.slice(0, 20)) {
  lines.push(
    `| \`${f.file}\` | ${f.totalLines} | ${f.hitLines} | ${f.coverage.toFixed(1)}% |`,
  );
}
lines.push("");

lines.push("## Security / crypto hot spots (< 60% coverage)");
lines.push("");
lines.push(
  "Heuristic match on path keywords: " +
    SECURITY_KEYWORDS.map((k) => `\`${k}\``).join(", "),
);
lines.push("");
if (hotSpots.length === 0) {
  lines.push("_(No security-keyword-matched files below 60% coverage.)_");
} else {
  lines.push("| File | Lines | Covered | Coverage |");
  lines.push("|---|---|---|---|");
  for (const f of hotSpots) {
    lines.push(
      `| \`${f.file}\` | ${f.totalLines} | ${f.hitLines} | ${f.coverage.toFixed(1)}% |`,
    );
  }
}
lines.push("");

lines.push("## Phase F1 test candidates");
lines.push("");
lines.push(
  "Cross-reference the hot spots table with Phase A journal deferred items",
);
lines.push("(`docs/bug-sweep/journal-2026-04-16.md`). Pick 4-6 files that :");
lines.push("");
lines.push("1. Are in the hot spots table above, AND");
lines.push(
  "2. Were flagged in Phase A (security gaps, P0 fixes, deferred items),",
);
lines.push("3. OR contain security/crypto logic per inspection.");
lines.push("");
lines.push(
  "Write regression tests covering the specific lines previously uncovered.",
);
lines.push("");

writeFileSync(OUT, lines.join("\n"), "utf-8");
console.log(`Wrote ${OUT}`);
console.log(
  `Workspace: ${globalPct.toFixed(2)}% coverage (${globalHit}/${globalTotal})`,
);
console.log(`Hot spots: ${hotSpots.length} files`);
