//! Stateless HMAC-signed FlowState for OAuth callbacks.

use crate::protocol::OAuthPurpose;
use chrono::Utc;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

/// Default lifetime of a FlowState token (10 minutes).
pub const FLOW_STATE_TTL_SECONDS: i64 = 600;

/// Errors from state signing/verification.
#[derive(Debug, Error)]
pub enum StateError {
    /// State token is malformed (missing separator, invalid base64, etc).
    #[error("malformed state token")]
    Malformed,
    /// HMAC signature does not verify.
    #[error("bad signature")]
    BadSignature,
    /// State has expired past its `expires_at` timestamp.
    #[error("state expired")]
    Expired,
    /// JSON deserialization of the payload failed.
    #[error("invalid state payload: {0}")]
    InvalidPayload(#[from] serde_json::Error),
}

/// The payload carried in the OAuth `state` query parameter.
///
/// Stateless design: the state machine keeps no server-side session.
/// All flow context rides in this struct, which is JSON-serialized,
/// then HMAC-signed via [`FlowState::sign`] and base64url-encoded.
/// The signed form is passed to the provider as the `state` param and
/// returned verbatim in the callback URL.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlowState {
    /// Unique ID for this flow (logging, debug, analytics).
    pub flow_id: Uuid,
    /// The user initiating the flow (None for Login purpose — no session yet).
    pub user_id: Option<Uuid>,
    /// Tenant this flow belongs to.
    pub tenant_id: Uuid,
    /// Provider key (matches catalog.json entry or oauth_providers.key).
    pub provider_key: String,
    /// Login (SSO) or Integration (mail/calendar/drive/social).
    pub purpose: OAuthPurpose,
    /// Where to redirect the user after the flow completes.
    pub redirect_after: Option<String>,
    /// PKCE code verifier (if the provider requires PKCE).
    pub pkce_verifier: Option<String>,
    /// Anti-CSRF nonce — 32 random bytes base64-encoded.
    pub nonce: String,
    /// Unix timestamp (seconds) when the state was signed.
    pub issued_at: i64,
    /// Unix timestamp (seconds) after which the state is rejected.
    pub expires_at: i64,
    /// Scopes the caller requested.
    pub requested_scopes: Vec<String>,
    /// If the user supplied their own client_id/secret via oauth_user_overrides.
    pub override_client_id: Option<Uuid>,
}

impl FlowState {
    /// Build a fresh FlowState, setting issued_at and expires_at to
    /// now and now+TTL respectively.
    ///
    /// The caller is responsible for supplying the rest of the fields.
    #[must_use]
    pub fn new(
        tenant_id: Uuid,
        provider_key: String,
        purpose: OAuthPurpose,
        nonce: String,
    ) -> Self {
        let now = Utc::now().timestamp();
        Self {
            flow_id: Uuid::new_v4(),
            user_id: None,
            tenant_id,
            provider_key,
            purpose,
            redirect_after: None,
            pkce_verifier: None,
            nonce,
            issued_at: now,
            expires_at: now + FLOW_STATE_TTL_SECONDS,
            requested_scopes: Vec::new(),
            override_client_id: None,
        }
    }

    /// True if the state has already expired at the current time.
    #[must_use]
    pub fn is_expired(&self) -> bool {
        Utc::now().timestamp() > self.expires_at
    }

    /// Sign this state with the given HMAC secret and return the
    /// base64url-encoded `payload.signature` token.
    ///
    /// The secret must be at least 32 bytes (enforced by caller; no
    /// runtime check here to avoid panic paths — use a 32-byte key
    /// generated by `openssl rand -hex 32` or similar).
    ///
    /// # Panics
    ///
    /// Never — HMAC-SHA256 accepts any key length, and JSON serialization
    /// of our owned-String fields is infallible.
    #[must_use]
    pub fn sign(&self, secret: &[u8]) -> String {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
        use hmac::{Hmac, Mac};
        use sha2::Sha256;

        let payload = serde_json::to_vec(self).expect("FlowState serialize never fails");
        let payload_b64 = URL_SAFE_NO_PAD.encode(&payload);

        let mut mac = Hmac::<Sha256>::new_from_slice(secret).expect("HMAC accepts any key size");
        mac.update(payload_b64.as_bytes());
        let sig = mac.finalize().into_bytes();
        let sig_b64 = URL_SAFE_NO_PAD.encode(sig);

        format!("{payload_b64}.{sig_b64}")
    }

    /// Verify a signed state token and deserialize the payload.
    ///
    /// # Errors
    ///
    /// - [`StateError::Malformed`] if the token is missing the `.`
    ///   separator or has invalid base64url
    /// - [`StateError::BadSignature`] if the HMAC does not match
    /// - [`StateError::Expired`] if `expires_at` is in the past
    /// - [`StateError::InvalidPayload`] if the payload JSON is malformed
    pub fn verify(token: &str, secret: &[u8]) -> Result<Self, StateError> {
        use base64::{engine::general_purpose::URL_SAFE_NO_PAD, Engine as _};
        use hmac::{Hmac, Mac};
        use sha2::Sha256;
        use subtle::ConstantTimeEq;

        let (payload_b64, sig_b64) = token.split_once('.').ok_or(StateError::Malformed)?;
        let payload = URL_SAFE_NO_PAD
            .decode(payload_b64)
            .map_err(|_| StateError::Malformed)?;
        let sig = URL_SAFE_NO_PAD
            .decode(sig_b64)
            .map_err(|_| StateError::Malformed)?;

        // Verify HMAC in constant time
        let mut mac = Hmac::<Sha256>::new_from_slice(secret).expect("HMAC accepts any key size");
        mac.update(payload_b64.as_bytes());
        let expected = mac.finalize().into_bytes();

        if sig.ct_eq(&expected).unwrap_u8() != 1 {
            return Err(StateError::BadSignature);
        }

        let state: FlowState = serde_json::from_slice(&payload)?;
        if state.is_expired() {
            return Err(StateError::Expired);
        }
        Ok(state)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_sets_issued_and_expires() {
        let s = FlowState::new(
            Uuid::new_v4(),
            "google".to_string(),
            OAuthPurpose::Login,
            "nonce123".to_string(),
        );
        assert!(s.expires_at > s.issued_at);
        assert_eq!(s.expires_at - s.issued_at, FLOW_STATE_TTL_SECONDS);
        assert_eq!(s.purpose, OAuthPurpose::Login);
        assert!(!s.is_expired(), "fresh state should not be expired");
    }

    #[test]
    fn manually_expired_state_detected() {
        let mut s = FlowState::new(
            Uuid::new_v4(),
            "x".into(),
            OAuthPurpose::Login,
            "n".into(),
        );
        s.expires_at = 0; // in the past
        assert!(s.is_expired());
    }

    #[test]
    fn serde_roundtrips() {
        let s = FlowState::new(
            Uuid::new_v4(),
            "microsoft".into(),
            OAuthPurpose::Integration,
            "nonceABCDEF".into(),
        );
        let json = serde_json::to_string(&s).unwrap();
        let back: FlowState = serde_json::from_str(&json).unwrap();
        assert_eq!(back.flow_id, s.flow_id);
        assert_eq!(back.provider_key, s.provider_key);
        assert_eq!(back.purpose, s.purpose);
    }
}
